WebMusicPlayer/musics/urls.py
from lib2to3.fixes.fix_input import context

from django.urls import path, include
from WebMusicPlayer.musics import views

urlpatterns = [
    path('', views.index, name='index'),
    path('album/', include([
        path('create/', views.create_album, name='create_album'),
        path('details/<int:pk>/', views.album_details, name='album_details'),
        path('edit/<int:pk>/', views.edit_album, name='edit_album'),
        path('delete/<int:pk>/', views.delete_album, name='delete_album'),
    ])),
    path('song/', include([
        path('create/', views.create_song, name='create_song'),
        path('play-song/<int:pk>/', views.play_song, name='play song'),
        path('serve-song/<int:pk>', views.serve_song, name='serve song'),
    ])),
]

WebMusicPlayer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('WebMusicPlayer.musics.urls')),
]

WebMusicPlayer/musics/models.py
from django.db import models
from sqlalchemy import Column, Integer, String, Float, ForeignKey, LargeBinary
from sqlalchemy.orm import relationship

from WebMusicPlayer.settings import Base


class Album(Base):

    __tablename__ = "albums"

    id = Column(
        Integer,
        primary_key=True,
    )

    album_name = Column(
        String(30),
        nullable=False,
        unique=True,
    )

    image_url = Column(
        String(250),
        nullable=False,
    )

    price = Column(
        Float,
        nullable=False,
    )

    songs = relationship(
        "Song",
        back_populates="album",
        cascade="all, delete-orphan",
    )

class Song(Base):

    __tablename__ = "songs"

    id = Column(
        Integer,
        primary_key=True,
    )

    song_name = Column(
        String(100),
        nullable=False,
    )

    music_file_data = Column(
        LargeBinary,
    )

    album_id = Column(
        Integer,
        ForeignKey("albums.id"),
        nullable=False,
    )

    album = relationship(
        "Album",
        back_populates="songs",
    )

WebMusicPlayer/musics/forms.py
from django import forms

from WebMusicPlayer.common.session_decorator import session_decorator
from WebMusicPlayer.musics.models import Album, Song
from WebMusicPlayer.settings import session


class AlbumBaseForm(forms.Form):
    album_name = forms.CharField(
        label='Album Name: ',
        max_length=30,
        required=True,
    )

    image_url = forms.URLField(
        label='Album Image URL: ',
        required=True,
    )

    price = forms.DecimalField(
        label='Price: ',
        required=True,
        min_value=0.0,
    )


class AlbumCreateForm(AlbumBaseForm):

    @session_decorator(session)
    def save(self):
        new_album = Album(
            album_name=self.cleaned_data['album_name'],
            image_url=self.cleaned_data['image_url'],
            price=self.cleaned_data['price'],
        )

        session.add(new_album)


class AlbumEditForm(AlbumBaseForm):

    def save(self, album):
        album.album_name = self.cleaned_data['album_name']
        album.image_url = self.cleaned_data['image_url']
        album.price = self.cleaned_data['price']


class AlbumDeleteForm(AlbumBaseForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['disabled'] = True


class SongBaseForm(forms.Form):
    song_name = forms.CharField(
        label='Song Name:',
        max_length=100,
        required=True,
    )

    album = forms.ChoiceField(
        label='Album:',
        choices=[],
    )

    music_file_data = forms.FileField(
        label='Music File:',
        required=True,
    )

    @session_decorator(session)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        albums = session.query(Album).all()
        self.fields['album'].choices = [(album.id, album.album_name) for album in albums]


class SongCreateForm(SongBaseForm):
    @session_decorator(session)
    def save(self, request):
        new_song = Song(
            song_name=self.cleaned_data['song_name'],
            album_id=self.cleaned_data['album'],
            music_file_data=request.FILES['music_file_data'].read(),
        )

        session.add(new_song)

WebMusicPlayer/musics/views.py
from lib2to3.fixes.fix_input import context

from django.http import HttpResponse
from django.shortcuts import render, redirect

from WebMusicPlayer.common.session_decorator import session_decorator
from WebMusicPlayer.musics.forms import SongCreateForm, AlbumCreateForm, AlbumEditForm, AlbumDeleteForm
from WebMusicPlayer.musics.models import Album, Song
from WebMusicPlayer.settings import session


@session_decorator(session)
def index(request):
    albums = session.query(Album).all()
    context = {
        'albums': albums,
    }
    return render(request, 'common/index.html', context)

def create_album(request):

    if request.method == 'GET':
        form = AlbumCreateForm()
    else:
        form = AlbumCreateForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('index')

    context = {
        'form': form,
    }

    return render(request, 'albums/create-album.html', context)

@session_decorator(session)
def edit_album(request, pk: int):
    album = session.query(Album).filter(Album.id == pk).first()

    if request.method == 'GET':
        form = AlbumEditForm(initial={
            'album_name': album.album_name,
            'image_url': album.image_url,
            'price': album.price,
        })

    else:
        form = AlbumEditForm(request.POST)
        if form.is_valid():
            form.save(album)
            return redirect('index')

    context = {
        'album': album,
        'form': form,
    }

    return render(request, 'albums/edit-album.html', context)

def delete_album(request, pk: int):

    album = (session.query(Album).filter(Album.id == pk).first())
    
    if request.method == 'GET':
        form = AlbumDeleteForm(
            initial={
                'album_name': album.album_name,
                'image_url': album.image_url,
                'price': album.price,
            })
    else:
        # form = AlbumDeleteForm(request.POST)
        #
        # if form.is_valid():
        session.delete(album)
        return redirect('index')

    context = {
        'album': album,
        'form': form,
    }
        

    return render(request, 'albums/delete-album.html', context)

@session_decorator(session)
def album_details(request, pk: int):
    album = session.query(Album).filter(Album.id == pk).first()
    context = {
        "album": album,
    }
    return render(request, 'albums/album-details.html', context)

def create_song(request):

    if request.method == 'GET':
        form = SongCreateForm()
    else:
        form = SongCreateForm(request.POST, request.FILES)

        if form.is_valid():
            form.save(request)
            return redirect('index')

    context = {
        'form': form,
    }

    return render(request, 'songs/create-song.html', context)

@session_decorator(session)
def play_song(request, pk: int):
    """
    Greps the song and returns the song as an object
    """

    song = session.query(Song).filter(Song.id == pk).first()

    context = {
        'song': song,
    }

    return render(request, 'songs/music-player.html', context)



@session_decorator(session)
def serve_song(request, pk: int):

    """
    Greps the song from the database and provides it to the serve.
    """
    song = session.query(Song).filter(Song.id == pk).first()

    if song:
        response = HttpResponse(song.music_file_data, content_type='audio/mpeg')
        response['Content-Disposition'] = f'inline; filename="{song.song_name}.mp3"'

        return response

    else:
        return HttpResponse('Song not found', status=404)

templates/albums/album-details.html
{% extends 'common/base.html' %}
{% block content %}

    <!--Details Page-->
    <section id="detailsPage">
        <div class="wrapper">

            <div class="albumCover">
                <!-- Album Image -->
                <img src="{{ album.image_url }}" alt="Cover Image">
            </div>

            <div class="albumInfo">

                <div class="albumText">
                    <!-- Album Info -->
                        <h1 class="album-title">Album Name: {{ album.album_name }}</h1>
{#                    <h4>Price: ${{ album.price }}</h4>#}
                        <p class="songs-text">SONGS</p> 
                        {#                    {% for song in album.songs %}#}
                        {#                        <a href="{% url 'play song' song.id %}"> {{ song.song_name }} </a>#}
                        {#                        {% if not forloop.last %} \n {% endif %}#}
                        {#                    {% endfor %}#}
{#                        <h4>Songs:</h4>#}
                        {% for song in album.songs %}
                            <p><a href="{% url 'play song' song.id %}" class="song-name">{{ song.song_name }}</a></p>
                        {% endfor %}
                    </h4>
                </div>

                <div class="actionBtn">
                    <!-- Album Buttons -->
                    <a href="{% url 'edit_album' album.id %}" class="edit">Edit</a>
                    <a href="{% url 'delete_album' album.id %}" class="remove">Delete</a>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/albums/create-album.html
{% extends 'common/base.html' %}
{% block content%}
<!--Create Page-->
<section class="createPage">

    <form action="{% url 'create_album' %}" method="post">
        <fieldset>
            <legend>Add Album</legend>
            <div class="container">
                
                {{ form }}
                {% csrf_token %}

                <!-- Form for Adding Album -->
{#                <label for="name">Album Name:</label>#}
{#                <input id="name" type="text" required>#}
{##}
{#                <label for="imgUrl">Image URL:</label>#}
{#                <input id="imgUrl" type="url" required>#}
{##}
{#                <label for="price">Price:</label>#}
{#                <input id="price" type="number" required>#}

                <!-- Button for Adding Album -->
                <button class="add-album" type="submit">Add New Album</button>
            </div>
        </fieldset>
    </form>
</section>

{% endblock %}

templates/albums/delete-album.html
{% extends 'common/base.html' %}
{% block content%}
<!--Edit Page-->
<section class="editPage">
    <form method="post" action="{% url 'delete_album' album.id %}">
        <fieldset>
            <legend>Delete Album</legend>
            <div class="container">
                {{ form }}
                {% csrf_token %}

                <!-- Form for Deleting an Album -->
{#                <label for="name">Album Name:</label>#}
{#                <input id="name" name="name" class="name" type="text" value="In These Silent Days" disabled="" readonly>#}
{##}
{#                <label for="imgUrl">Image URL:</label>#}
{#                <input id="imgUrl" name="imgUrl" class="imgUrl" type="url"#}
{#                       value="https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2021%2F07%2F20%2FBrandiCarlile-AlbumCover-Web.jpg"#}
{#                       disabled readonly>#}
{##}
{#                <label for="price">Price:</label>#}
{#                <input id="price" name="price" class="price" type="number" value="12.8" disabled="" readonly>#}

                <!-- Button for Deleting an Album -->
                <button class="delete-album" type="submit">Delete Album</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

templates/albums/edit-album.html
{% extends 'common/base.html' %}
{% block content%}
<!--Edit Page-->
<section class="editPage">
    <form method="post" action="{% url 'edit_album' album.id %}">
        <fieldset>
            <legend>Edit Album</legend>
            <div class="container">
                {{ form }}
                {% csrf_token %}

                <!-- Form for Editing Album -->
{#                <label for="name">Album Name:</label>#}
{#                <input id="name" name="name" class="name" type="text" value="In These Silent Days">#}
{##}
{#                <label for="imgUrl">Image URL:</label>#}
{#                <input id="imgUrl" name="imgUrl" class="imgUrl" type="text"#}
{#                       value="https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2021%2F07%2F20%2FBrandiCarlile-AlbumCover-Web.jpg">#}
{##}
{#                <label for="price">Price:</label>#}
{#                <input id="price" name="price" class="price" type="text" value="12.8">#}

                <!-- Button for Editing Album -->
                <button class="edit-album" type="submit">Edit Album</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <title>Web Beats</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="icon" href="/static/images/favicon.ico" type="image/x-icon">
</head>

<body>
<div id="box">

    <!-- Navigation Bar -->
    <header>
        <nav>
            <img src="{% static 'images/cute-dancing.gif' %}" alt="headphones">
            <a href="{% url 'index' %}">Home</a><ul></ul>
            <ul>
                <li><a href="{% url 'create_album' %}">Create Album</a></li>
                <li><a href="{% url 'create_song' %}">Create Song</a></li>
            </ul>
        </nav>
    </header>
    <!-- End Navigation Bar -->

    <!-- Main Content -->
    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer>
        <div>
            &copy; TSVTLN@GITHUB. All rights reserved.
        </div>
    </footer>
    <!-- End Footer -->

</div>
</body>
</html>

templates/common/index.html
{% extends 'common/base.html' %}
{% block content %}

    <!-- Catalog with Albums-->
    <section id="catalogPage">
        {% if albums %}

            <!-- If albums in catalog -->
            <h1>All Albums</h1>
            {% for album in albums %}
            <!-- First Card-Box in catalog -->
                <div class="card-box">
                    <img src="{{ album.image_url }}" alt="Cover Image">
                    <div>
                        <div class="text-center">
                            <p class="album-name">Name: {{ album.album_name }}</p>
{#                            <p class="price">Price: ${{ album.price }}</p>#}
                        </div>
                        <div class="btn-group">
                            <a href="{% url 'album_details' album.id %}">Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <!--  If No albums in catalog -->
            <p>No Albums in Catalog!</p>
        {% endif %}

    </section>

{% endblock %}

templates/songs/create-song.html
{% extends 'common/base.html' %}
{% block content%}
<!--Create Page-->
<section class="createPage">

    <form action="{% url 'create_song' %}" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Add Album</legend>
            <div class="container">
                
                {{ form }}
                {% csrf_token %}

{#                <!-- Form for Song Album -->#}
{#                <label for="name">Song Name:</label>#}
{#                <input id="name" type="text" required>#}
{##}
{#                <select name="album" id="id_album">#}
{#                    <option value="1">In These Silent Days</option>#}
{#                    <option value="2">The Dark Side of the Moon</option>#}
{#                    <option value="3">Melodrama</option>#}
{#                </select>#}

                <!-- Button for Song Album -->
                <button class="add-song" type="submit">Add New Song</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}